### ISSUE TITLE
Error with tsoutliers on install

### ISSUE THREAD

**Issue by abfleishman** [eldarrak/FLightR#12]
Tried to install and got following error:

`install_github("eldarrak/FLightR")`

> Downloading GitHub repo eldarrak/FLightR@master
> Installing FLightR
> Skipping 1 packages not available: tsoutliers
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
>   '/private/var/folders/HJ/HJsTXtLSFq8pUyLOZ9ium++++TI/-Tmp-/Rtmp0UpYPb/devtools34477d800f6/eldarrak-FLightR-5478d1d'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 
> 
> ERROR: dependency ‘tsoutliers’ is not available for package ‘FLightR’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/FLightR’
> Error: Command failed (1)

I am running the following version of R in Rstudio:
`version`
>               _                           
> platform       x86_64-apple-darwin10.8.0   
> arch           x86_64                      
> os             darwin10.8.0                
> system         x86_64, darwin10.8.0        
> status                                     
> major          3                           
> minor          2.1                         
> year           2015                        
> month          06                          
> day            18                          
> svn rev        68531                       
> language       R                           
> version.string R version 3.2.1 (2015-06-18)
> nickname       World-Famous Astronaut   

Thoughts?

**Comment by eldarrak** [comment]
It looks like tsoutliers is not available for your system. I have changed dependencies, so FLightR should work now except one function. Let me know whether you can install it now.
```{r} 
library(devtools)
install_github('eldarrak/FLightR@0.4.0')
```
