### ISSUE TITLE
run.particle.filter Error Warnings

### ISSUE THREAD

**Issue by JasonMHill** [eldarrak/FLightR#15]
options(nwarnings = 10000)
Result.S752<-run.particle.filter(all.in,nParticles=1e6,known.last=FALSE, check.outliers=T,b=500)

Produces 800+ warnings, alternating between 
In Current.Weights[Index.Stable] * in.Data$Spatial$Behav.mask[New.Particles] :  longer object length is not a multiple of shorter object length

and

In pf.run.parallel.SO.resample(in.Data = all.out, threads = Threads,  ... :
  number of items to replace is not a multiple of replacement length

I've gotten these error warnings with the first four birds that I have processed. Changing the settings for outlier detection, nParticles or b doesn't halt the warnings. Is it safe to ignore these warnings? The results look reasonable. Thank you.

**Comment by eldarrak** [comment]
Thanks for posting here Jason!
 There was a bug in the behavioural mask.. Fixed now.
I would rerun the tags you have done before.
  Cheers

**Comment by eldarrak** [comment]
forgot to tell, you have to reinstall FLightR
```
devtools::install_github('eldarrak/FLightR')
```

**Comment by JasonMHill** [comment]
Many thanks Eldar!
