### ISSUE TITLE
Inconsistent Enforcement of the Spatial Mask

### ISSUE THREAD

**Issue by JasonMHill** [eldarrak/FLightR#16]
First, FlightR rocks and thank you Eldar for your tireless work on this package. What an awesome leap forward for geolocator analysis. I have been systematically working through the coding options in FlightR to better understand the underlying model, but I seem to be observing some behavior that I can’t understand in regards to onshore/offshore locations and the spatial mask. I am analyzing geolocator data from East Coast US Grasshopper Sparrows: a North American landbird that migrates to Florida and some of the Caribbean Islands. So I want to allow flights over water, but stationary periods over water are not possible. 
However, when I export my results to ArcGIS and look at the movements, I am getting stationary periods over water >50 km from land. I understand that the spatial grid is 50x50 km, so a stationary period just offshore (in nearshore waters) is reasonable given the coarseness of the spatial grid. 

#Attempt 1: Do not allow stationary periods over water
Grid<-make.grid(left=-115, bottom=-10, right=-60, top=52,
                distance.from.land.allowed.to.use=c(-Inf, **1500**),**probability.of.staying = 0**,
                distance.from.land.allowed.to.stay=c(-Inf, **0**))
all.in<-make.prerun.object(Proc.data, Grid,start=c(-76.4181, 38.2942),end = NA,
                         Direction=180,) 
Result.U337_NoWaterStay<-run.particle.filter(all.in,nParticles=1e6,known.last=FALSE,
                                  check.outliers=T, b=750)

The blue box surrounds some of the points >50 km from land; these points represent 30 consecutive days).
![nowater](https://cloud.githubusercontent.com/assets/13423263/19692339/984ebaa4-9aa5-11e6-80d8-16ddef1dd9f3.jpg)

When I check the spatial grid, I can confirm that there is a zero probability of staying there.
> all.in$Spatial$Grid[5972,]
      lon       lat      Stay 
-81.63934  23.85000   0.00000 
> all.in$Spatial$Grid[5972,3]==0
Stay 
TRUE 

Plotting the grid (via make.grid(…..) also confirms that the mask ‘looks’ right. A bird shouldn’t be able to hang out there for a month, I think.

#Attempt 2: A more extreme example, do not allow **ANY** flight over water (>50 km from shore)
Grid<-make.grid(left=-115, bottom=-10, right=-60, top=52,
                distance.from.land.allowed.to.use=c(-Inf, **0**),probability.of.staying = **0**,
                distance.from.land.allowed.to.stay=c(-Inf, **0**))

I understand that in this case the make.grid function resets the maximum distance.from.land.allowed.to.stay to 25 km, 
head(getAnywhere(make.grid()))
…
if (distance.from.land.allowed.to.stay[2] < 25) 
        distance.from.land.allowed.to.stay[2] <- 25
…
But, I am still getting flights over water (>100 km offshore Florida) and short stationary periods over water. In this photo there’s a 4-day period of _flight_ over water far from shore. 

![nowaterforreal](https://cloud.githubusercontent.com/assets/13423263/19692414/dab65ece-9aa5-11e6-8dd0-e09a8c0fbdf0.jpg)

Perhaps I'm misunderstanding the "distance.from.land.allowed.to.stay" command. My understanding is that an animal cannot remain in that 50x50 km square for multiple twilight periods if I set probability.of.staying to zero for that square. Thanks for your help Eldar.

**Comment by JasonMHill** [comment]
First, FlightR rocks and thank you Eldar for your tireless work on this package. What an awesome leap forward for geolocator analysis. I have been systematically working through the coding options in FlightR to better understand the underlying model, but I seem to be observing some behavior that I can’t understand in regards to onshore/offshore locations and the spatial mask. I am analyzing geolocator data from East Coast US Grasshopper Sparrows: a North American landbird that migrates to Florida and some of the Caribbean Islands. So I want to allow flights over water, but stationary periods over water are not possible. 
However, when I export my results to ArcGIS and look at the movements, I am getting stationary periods over water >50 km from land. I understand that the spatial grid is 50x50 km, so a stationary period just offshore (in nearshore waters) is reasonable given the coarseness of the spatial grid. 

#Attempt 1: Do not allow stationary periods over water
Grid<-make.grid(left=-115, bottom=-10, right=-60, top=52,
                distance.from.land.allowed.to.use=c(-Inf, **1500**),**probability.of.staying = 0**,
                distance.from.land.allowed.to.stay=c(-Inf, **0**))
all.in<-make.prerun.object(Proc.data, Grid,start=c(-76.4181, 38.2942),end = NA,
                         Direction=180,) 
Result.U337_NoWaterStay<-run.particle.filter(all.in,nParticles=1e6,known.last=FALSE,
                                  check.outliers=T, b=750)

The blue box surrounds some of the points >50 km from land; these points represent 30 consecutive days).
![nowater](https://cloud.githubusercontent.com/assets/13423263/19692339/984ebaa4-9aa5-11e6-80d8-16ddef1dd9f3.jpg)

When I check the spatial grid, I can confirm that there is a zero probability of staying there.
> all.in$Spatial$Grid[5972,]
      lon       lat      Stay 
-81.63934  23.85000   0.00000 
> all.in$Spatial$Grid[5972,3]==0
Stay 
TRUE 

Plotting the grid (via make.grid(…..) also confirms that the mask ‘looks’ right. A bird shouldn’t be able to hang out there for a month, I think.

#Attempt 2: A more extreme example, do not allow **ANY** flight over water (>50 km from shore)
Grid<-make.grid(left=-115, bottom=-10, right=-60, top=52,
                distance.from.land.allowed.to.use=c(-Inf, **0**),probability.of.staying = **0**,
                distance.from.land.allowed.to.stay=c(-Inf, **0**))

I understand that in this case the make.grid function resets the maximum distance.from.land.allowed.to.stay to 25 km, 
head(getAnywhere(make.grid()))
…
if (distance.from.land.allowed.to.stay[2] < 25) 
        distance.from.land.allowed.to.stay[2] <- 25
…
But, I am still getting flights over water (>100 km offshore Florida) and short stationary periods over water. In this photo there’s a 4-day period of _flight_ over water far from shore. 

![nowaterforreal](https://cloud.githubusercontent.com/assets/13423263/19692414/dab65ece-9aa5-11e6-8dd0-e09a8c0fbdf0.jpg)

Perhaps I'm misunderstanding the "distance.from.land.allowed.to.stay" command. My understanding is that an animal cannot remain in that 50x50 km square for multiple twilight periods if I set probability.of.staying to zero for that square. Thanks for your help Eldar.

**Comment by eldarrak** [comment]
Hi Jason,
 I think you observe normal behaviour but not a bug.
1. The first thing is to look at what are you actually plotting. It looks to me like you plot mean coordinates, that are estimated over all million particles, so in example 1 you likely have a group of points sitting at the island and another one on the mainland. You should try plotting a specific result with `plot.util.distr()` function for specific days to see what is really happening.
2. Your second example should also be looked in more detail, but I remember that I fix minimum distance to ~ 50 km.
 In general I would work first without masks and outlier detection to see what are the problems.. If you see symmetrical patterns in drifts up and down (as I see on your first figure) it very likely means that either your calibration is off or you data are very shady. In first case try improving that in the second - you cannot do much, but do not over-interpret your data and always use uncertainty FLightR provides with the estimates.

**Comment by JasonMHill** [comment]
Hello Eldar,
1. Yes, excellent. Plotting the median values confirms that the mask is indeed enforcing the zero probability of offshore locations. You are absolutely right, some of the particles are showing up on Florida, and some on Cuba, resulting in the mean values being in the ocean. I should have thought of that--my mistake. Duh!  +1 for making sure to keep the uncertainty in mind--I appreciate that each of these locations has (in my case) several hundred kilometers of error around them. 

2. I can confirm with the latest version of FlightR that the distance.from.land.allowed.to.stay[2] equals 25 km in my result output  when I set the distance.from.land.allowed.to.stay=c(-Inf, 0). 
[str(Result$Spatial$Grid)]
...
- attr(*, "distance.from.land.allowed.to.stay")= num [1:2] -Inf 25

I will try some longer calibration distances, thank you for that suggestion. Let's close this issue. Thanks again.
