### ISSUE TITLE
Error in make.calibration: could not find function "varExp"

### ISSUE THREAD

**Issue by JasonMHill** [eldarrak/FLightR#17]
> packageVersion("FlightR")
[1] ‘0.4.3’

I just started getting an error message when using the make.calibration command. All packages and R are updated and running fine otherwise. First time I’ve seen this error. I'm seeing it when rerunning tags (from saved files) and when running new tags. 

> Calibration.periods
  calibration.start calibration.stop      lon     lat
2015-06-01      2015-09-01 -96.8224 39.2082

Calibration<-make.calibration(Proc.data.U357, Calibration.periods)
…
checking dusk 74 
checking dusk 75 
checking dusk 76 
calibration method used: parametric.slope 
  estimating correction function...

**Error in eval(expr, envir, enclos) : could not find function "varExp"**

**Comment by eldarrak** [comment]
Thanks Jason!
 I moved package dependences to Imports from in order to get to CRAN submission, so there might be some small problems here and there. Should work now.
