### ISSUE TITLE
dependencies on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [eldarrak/FLightR#24]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

'maptools', 'rgdal', 'rgeos' are used, speciffically as found by `pkgapi`: maptools::gzAzimuth maptools::sunriset rgeos::gBuffer rgeos::gDistance rgeos::gSimplify rgeos::gUnion rgeos::gWithinDistance Please see https://r-spatial.org/r/2023/04/10/evolution3.html for links to possible substitutes, work is ongoing to keep maptools::sunriset active in some way.

Action is needed soon, best by June, latest by October 2023.

**Comment by rsbivand** [comment]
Please collaborate with other users of sun methods to find a suitable resolution.

**Comment by rsbivand** [comment]
@eldarrak @Biserkov @aurielfournier @JKaragicheva the most recent release does not address this issue. In four weeks, three packages imported here will be archived and consequently all CRAN ckecks will fail. You must act immediately to replace `rgdal`, `rgeos` and `maptools`.

**Comment by eldarrak** [comment]
we are working on it, so the new version will come in the coming weeks.

**Comment by rsbivand** [comment]
@eldarrak OK, thanks. Most likely date for archiving retiring packages in week 42, so aim to be published on CRAN before then, please.

**Comment by eldarrak** [comment]
solved with 0.5.4
