### ISSUE TITLE
no application method for 'st_as_sf' applied to an object of class "c('matrix','array','double','numeric')"

### ISSUE THREAD

**Issue by toddeast** [eldarrak/FLightR#29]
Hello.  I'm attempting to run the FlightR_analysis_workflow.Rmd example process.  I made it all the way to the 

stationary.migration.summar(Result, prob.cotoff = 0.1, min.say = 3)

The execution in the .Rmd file errors with the error I put in the title.

I'm using 
R 4.1.3
packageVersion("FLightR")
[1] ‘0.5.4’

FLightR::stationary.migration.summary()

I'd like to go through a "verification" test to make sure that all of the packages and their dependencies are installed and working before I attempt to use these tools for my samples.  I'm using Lotek fLight FL6057 tags.  I've made it to this function after the 40 minutes of processing.  Not complaining but hope I can pick back up from the saved file to complete the workflow.

Thanks for your time,
Todd Eastman

**Comment by eldarrak** [comment]
Hi Todd,
 Looks like an usse in the move from sp to sf in version 0.5.4.
 I will look into it shortly, but for now I advice you install the 0.5.3 version. 
  Best,
 Eldar

**Comment by toddeast** [comment]
Hi Eldar,

Thank you for your advice!  I'm downloading version 0.5.3 and will know soon if that fixes the issue.  I'm new to R :)

The installer asked me what to do about the dependent packages ...  Do you have any advice about choosing option 1, 2, or ... from below?

Todd

P.S.  It appears reading papers that you are on the team that came up with FLightR?!  I'm currently reading up on the papers and intrigued by the process.  I'm helping out a passionate field scientist who's not very software savvy to process his geolocator light data samples.  He used the Lotek fLight FL6057 tags.  I'm currently trying to figure out how to take this two column CSV file (date time, light) and convert it into the TAGS format to be used by FLightR.  Any advice you have here would be appreciated.

> install_version("FLightR", "0.5.3")
Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/FLightR/FLightR_0.5.3.tar.gz
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: fansi  (1.0.4  -> 1.0.5 ) [CRAN]
5: vctrs  (0.6.1  -> 0.6.3 ) [CRAN]
6: purrr  (1.0.1  -> 1.0.2 ) [CRAN]
7: curl   (5.0.0  -> 5.1.0 ) [CRAN]
8: Rcpp   (1.0.10 -> 1.0.11) [CRAN]
9: digest (0.6.31 -> 0.6.33) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3

**Comment by eldarrak** [comment]
Hi Todd,
 I would choose option 2. You might also need to restart R several times during the Rcpp installation... 
I suggest you make the tags formatted file with the TwGeos package... 
Have a look at the [geolocator user guide](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13036) 
you can also ask general geolocaiton questions [here](https://ornithologyexchange.org/forums/forum/259-geolocator-discussion-amp-support/)
Hope it helps,
  Eldar

**Comment by eldarrak** [comment]
I have updated the code, so please try the latest version out (from github).
  Best,
  Eldar
