### ISSUE TITLE
ERROR: dependency 'ggsn' is not available for package 'FLightR'

### ISSUE THREAD

**Issue by SwiftMeier** [eldarrak/FLightR#30]
Dear Eldar,

I am trying to use the latest FlightR version. However, I get this error message:

> devtools::install_github("eldarrak/FLightR", lib = "C:/Program Files/R/R-4.3.1/library/")
Downloading GitHub repo eldarrak/FLightR@HEAD
Skipping 1 packages not available: ggsn
── R CMD build ───────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\...\AppData\Local\Temp\Rtmpq6f6La\remotes1eb07525652e\eldarrak-FLightR-b74b3b5/DESCRIPTION' (506ms)
─  preparing 'FLightR': (492ms)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a 'data/datalist' file should be added
─  building 'FLightR_0.5.5.tar.gz'
ERROR: dependency 'ggsn' is not available for package 'FLightR'
removing 'C:/Program Files/R/R-4.3.1/library/FLightR'
Warnmeldung:
In i.p(...) :
  Installation des Pakets ‘C:/.../AppData/Local/Temp/Rtmpq6f6La/file1eb019427c29/FLightR_0.5.5.tar.gz’ hatte Exit-Status ungleich 0

Is it just me or is this a general issue? Is there an easy way arround?

Thank you for your help in advance & best wishes,
Christoph

**Comment by eldarrak** [comment]
Thank for catchig this one, Christoph!
I have removed the dependency (so not more scale bar ans nort line). I could bring them back if the package is back to CRAN. Will submit the new version ot CRAN in December, so use install_github() before that.
  Eldar

**Comment by SwiftMeier** [comment]
Dear Eldar,

Wow, thank you so much for reacting this fast. I sure you have more urgent things on your schedule.

Best wishes,
Christoph


Dr. Christoph Meier

Vogelzugforschung
Tel +41 41 462 99 23
Fax +41 41 462 97 10
***@***.***
http://www.vogelwarte.ch


Schweizerische Vogelwarte | Seerose 1 | CH-6204 Sempach | Schweiz
Station ornithologique suisse | Seerose 1 | CH-6204 Sempach | Suisse
Stazione ornitologica svizzera | Seerose 1 | CH-6204 Sempach |
Svizzera Swiss Ornithological Institute | Seerose 1 | CH-6204 Sempach | Switzerland

Willkommen im neuen Besuchszentrum in
Sempach!_http://www.vogelwarte.ch/de/besuch/
Bienvenue au nouveau centre de visite à
Sempach!_http://www.vogelwarte.ch/fr/visite/




Von: Eldar Rakhimberdiev ***@***.***>
Gesendet: Dienstag, 7. November 2023 14:10
An: eldarrak/FLightR ***@***.***>
Cc: Christoph Meier ***@***.***>; Author ***@***.***>
Betreff: Re: [eldarrak/FLightR] ERROR: dependency 'ggsn' is not available for package 'FLightR' (Issue #30)


Thank for catchig this one, Christoph!
I have removed the dependency (so not more scale bar ans nort line). I could bring them back if the package is back to CRAN. Will submit the new version ot CRAN in December, so use install_github() before that.
Eldar
